version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/rails/Dockerfile
    command: bundle exec puma -C config/puma.rb
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - public-data:/app/public
      - tmp-data:/app/tmp
    depends_on:
      - db
    tty: true
  db:
    image: mysql:5.7
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
  web:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - 80:80
    volumes:
      - public-data:/app/public
      - tmp-data:/app/tmp
    depends_on:
      - app
volumes:
  public-data:
  tmp-data:
  db-data:
